[package]
name = "win-mic-mute"
version = "0.1.0"
authors = ["Ionuț Botizan <ionut.botizan@gmail.com>"]
edition = "2018"

[dependencies.windows]
version = "0.46.0"
features = [
	"Win32_Foundation",
	"Win32_System_SystemServices",
	"Win32_UI_WindowsAndMessaging",
]